
language: java
sudo: required
#building, running the JUnit tests and the benchmarks
script: 
- mvn clean install
- java -jar target/Matrices-0.0.1-SNAPSHOT.jar com.testwo.Matrices.MyBenchmark.testMultIJK -p noRows=10 -rf csv -rff testIJK
- java -jar target/Matrices-0.0.1-SNAPSHOT.jar com.testwo.Matrices.MyBenchmark.testMultIKJ -p noRows=10 -rf csv -rff testIKJ
#don't want an email every time I commit
notifications:
  email: false
after_success:
#installing the required packages for the python script to run
- sudp apt-get -qq update
- sudo apt-get install -y python2.7
- sudo apt-get install -y python-numpy
- sudo apt-get install -y python-matplotlib
- chmod +x plotScript.py
#python script produces a graph of the results
- python plotScript.py
- chmod +x update-gh.sh 
#pushes back to github the graph and the results
- ./update-gh.sh
