language: java
sudo: false
script: 
- mvn clean install
- java -jar target/Matrices-0.0.1-SNAPSHOT.jar -p noRows=3 -e com.testtwo.Matrices.MyBenchmark.testMultIKJ -rf csv -rff test7
notifications:
  email: false
