
language: java
sudo: required
script: 
- mvn clean install
- java -jar target/Matrices-0.0.1-SNAPSHOT.jar com.testwo.Matrices.MyBenchmark.testMultIJK -p noRows=10 -rf csv -rff testIJK
- java -jar target/Matrices-0.0.1-SNAPSHOT.jar com.testwo.Matrices.MyBenchmark.testMultIKJ -p noRows=10 -rf csv -rff testIKJ
notifications:
  email: false
after_success:
- sudp apt-get -qq update
- sudo apt-get install -y python3.6
- sudo apt-get install -y python-numpy
- sudo apt-get install -y python-matplotlib
- sudo apt-get install -y python-csv
- sudo apt-get install -y python-time
- sudo apt-get install -y python-matplotlib.pyplot
- chmod +x plotScript.py
- python plotScript.py
- chmod +x update-gh.sh 
- ./update-gh.sh
